//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a asset.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atreemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a asset like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Atreemo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Atreemo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atreemo.Resources.Atreemo", typeof(Atreemo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string Account_FullTitle {
            get {
                return ResourceManager.GetString("Account_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string Account_Title {
            get {
                return ResourceManager.GetString("Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Account_Tooltip {
            get {
                return ResourceManager.GetString("Account_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation_FullTitle {
            get {
                return ResourceManager.GetString("Automation_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation_Title {
            get {
                return ResourceManager.GetString("Automation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation_Tooltip {
            get {
                return ResourceManager.GetString("Automation_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns_FullTitle {
            get {
                return ResourceManager.GetString("Campaigns_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns_Title {
            get {
                return ResourceManager.GetString("Campaigns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns_Tooltip {
            get {
                return ResourceManager.GetString("Campaigns_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company segmentation.
        /// </summary>
        public static string Company_FullTitle {
            get {
                return ResourceManager.GetString("Company_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company segmentation.
        /// </summary>
        public static string Company_Title {
            get {
                return ResourceManager.GetString("Company_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected as.
        /// </summary>
        public static string ConncetedAs {
            get {
                return ResourceManager.GetString("ConncetedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact segmentation.
        /// </summary>
        public static string Contact_FullTitle {
            get {
                return ResourceManager.GetString("Contact_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact segmentation.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_FullTitle {
            get {
                return ResourceManager.GetString("Dashboard_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Tooltip {
            get {
                return ResourceManager.GetString("Dashboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events_FullTitle {
            get {
                return ResourceManager.GetString("Events_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events_Title {
            get {
                return ResourceManager.GetString("Events_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events_Tooltip {
            get {
                return ResourceManager.GetString("Events_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback_FullTitle {
            get {
                return ResourceManager.GetString("Feedback_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback_Title {
            get {
                return ResourceManager.GetString("Feedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback_Tooltip {
            get {
                return ResourceManager.GetString("Feedback_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_FullTitle {
            get {
                return ResourceManager.GetString("Help_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Tooltip {
            get {
                return ResourceManager.GetString("Help_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        public static string Household {
            get {
                return ResourceManager.GetString("Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Households.
        /// </summary>
        public static string Households {
            get {
                return ResourceManager.GetString("Households", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string Insight_FullTitle {
            get {
                return ResourceManager.GetString("Insight_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string Insight_Title {
            get {
                return ResourceManager.GetString("Insight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string Insight_Tooltip {
            get {
                return ResourceManager.GetString("Insight_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Mapping_FullTitle {
            get {
                return ResourceManager.GetString("Mapping_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Mapping_Title {
            get {
                return ResourceManager.GetString("Mapping_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your data together with Google Maps&lt;br&gt; to visualise and leverage your data in new&lt;br&gt; ways. &lt;a href=&quot;#&quot; target=&apos;_blank&apos; style=&apos;color:#FFF&apos;&gt;Find out more&lt;/a&gt;.
        /// </summary>
        public static string Mapping_Tooltip {
            get {
                return ResourceManager.GetString("Mapping_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Salutation1 {
            get {
                return ResourceManager.GetString("Salutation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string Salutation2 {
            get {
                return ResourceManager.GetString("Salutation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Salutation3 {
            get {
                return ResourceManager.GetString("Salutation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signle Customer View.
        /// </summary>
        public static string SCV_FullTitle {
            get {
                return ResourceManager.GetString("SCV_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCV.
        /// </summary>
        public static string SCV_Title {
            get {
                return ResourceManager.GetString("SCV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Customer View.
        /// </summary>
        public static string SCV_Tooltip {
            get {
                return ResourceManager.GetString("SCV_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search company.
        /// </summary>
        public static string SearchCompany_FullTitle {
            get {
                return ResourceManager.GetString("SearchCompany_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search company.
        /// </summary>
        public static string SearchCompany_Title {
            get {
                return ResourceManager.GetString("SearchCompany_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contact.
        /// </summary>
        public static string SearchContact_FullTitle {
            get {
                return ResourceManager.GetString("SearchContact_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contact.
        /// </summary>
        public static string SearchContact_Title {
            get {
                return ResourceManager.GetString("SearchContact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support_FullTitle {
            get {
                return ResourceManager.GetString("Support_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support_Tooltip {
            get {
                return ResourceManager.GetString("Support_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys_FullTitle {
            get {
                return ResourceManager.GetString("Surveys_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys_Title {
            get {
                return ResourceManager.GetString("Surveys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys_Tooltip {
            get {
                return ResourceManager.GetString("Surveys_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user.
        /// </summary>
        public static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk_FullTitle {
            get {
                return ResourceManager.GetString("Talk_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk_Title {
            get {
                return ResourceManager.GetString("Talk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk_Tooltip {
            get {
                return ResourceManager.GetString("Talk_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsHeader1 {
            get {
                return ResourceManager.GetString("ToolsHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Actions.
        /// </summary>
        public static string ToolsHeader2 {
            get {
                return ResourceManager.GetString("ToolsHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Saved Work.
        /// </summary>
        public static string ToolsHeader3 {
            get {
                return ResourceManager.GetString("ToolsHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string ToolsHeader4 {
            get {
                return ResourceManager.GetString("ToolsHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement_FullTitle {
            get {
                return ResourceManager.GetString("UserManagement_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement_Title {
            get {
                return ResourceManager.GetString("UserManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all users.
        /// </summary>
        public static string UserManagement_Tooltip {
            get {
                return ResourceManager.GetString("UserManagement_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        public static string Vouchers_FullTitle {
            get {
                return ResourceManager.GetString("Vouchers_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        public static string Vouchers_Title {
            get {
                return ResourceManager.GetString("Vouchers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        public static string Vouchers_Tooltip {
            get {
                return ResourceManager.GetString("Vouchers_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what do you want to do today…..
        /// </summary>
        public static string WelcomeMessage1 {
            get {
                return ResourceManager.GetString("WelcomeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have not seen you for a while…..
        /// </summary>
        public static string WelcomeMessage2 {
            get {
                return ResourceManager.GetString("WelcomeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how are you today?.
        /// </summary>
        public static string WelcomeMessage3 {
            get {
                return ResourceManager.GetString("WelcomeMessage3", resourceCulture);
            }
        }
    }
}
