//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atreemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpTooltip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTooltip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atreemo.Resources.HelpTooltip", typeof(HelpTooltip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can build queries, view saved selections and load data files from the options below..
        /// </summary>
        public static string Helptooltip_1 {
            get {
                return ResourceManager.GetString("Helptooltip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a name for your selection so it is easy to identify later..
        /// </summary>
        public static string Helptooltip_10 {
            get {
                return ResourceManager.GetString("Helptooltip_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your Atreemo modules right here .
        /// </summary>
        public static string Helptooltip_101 {
            get {
                return ResourceManager.GetString("Helptooltip_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This panel will display your recent actions in Atreemo..
        /// </summary>
        public static string Helptooltip_102 {
            get {
                return ResourceManager.GetString("Helptooltip_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your saved work or projects your colleagues want to share with you here.
        /// </summary>
        public static string Helptooltip_103 {
            get {
                return ResourceManager.GetString("Helptooltip_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your dashboard and review key stats for your campaigns.
        /// </summary>
        public static string Helptooltip_104 {
            get {
                return ResourceManager.GetString("Helptooltip_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more information to help you and others identify what it includes and if necessary what it is for..
        /// </summary>
        public static string Helptooltip_11 {
            get {
                return ResourceManager.GetString("Helptooltip_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the tabs here and above to manage and do more with your selection..
        /// </summary>
        public static string Helptooltip_2 {
            get {
                return ResourceManager.GetString("Helptooltip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count shows the number of people in your selection at a contact level and a Household / Company level.
        /// </summary>
        public static string Helptooltip_3 {
            get {
                return ResourceManager.GetString("Helptooltip_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your survey description.  This is not customer facing, it is something that will help you identify the survey later.
        /// </summary>
        public static string Helptooltip_300 {
            get {
                return ResourceManager.GetString("Helptooltip_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your survey description. This is not customer facing, it is something that will help you identify the survey later.
        /// </summary>
        public static string Helptooltip_301 {
            get {
                return ResourceManager.GetString("Helptooltip_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add a logo to your survey. Click ‘Choose file’ to locate the file you want to use and then click ‘Upload’. You will then be able to see the placement of your logo when you preview the survey..
        /// </summary>
        public static string Helptooltip_302 {
            get {
                return ResourceManager.GetString("Helptooltip_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set the amount of space (in pixals) you want between questions here.
        /// </summary>
        public static string Helptooltip_303 {
            get {
                return ResourceManager.GetString("Helptooltip_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your survey title. This will appear at the top of the survey and if you post to Facebook and Twitter it will appear in the message that is posted..
        /// </summary>
        public static string Helptooltip_304 {
            get {
                return ResourceManager.GetString("Helptooltip_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your survey introduction. This will appear on the first page of your survey to tell the recipient more about it..
        /// </summary>
        public static string Helptooltip_305 {
            get {
                return ResourceManager.GetString("Helptooltip_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text will appear on a page presented once the survey has been completed.
        /// </summary>
        public static string Helptooltip_306 {
            get {
                return ResourceManager.GetString("Helptooltip_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a saved selection.
        /// </summary>
        public static string Helptooltip_4 {
            get {
                return ResourceManager.GetString("Helptooltip_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag operations.
        /// </summary>
        public static string Helptooltip_6 {
            get {
                return ResourceManager.GetString("Helptooltip_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your selection by dragging nodes to the window to the right..
        /// </summary>
        public static string Helptooltip_7 {
            get {
                return ResourceManager.GetString("Helptooltip_7", resourceCulture);
            }
        }
    }
}
