//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atreemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atreemo.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CpyID.
        /// </summary>
        public static string Company_CpyID {
            get {
                return ResourceManager.GetString("Company_CpyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        public static string Company_CpyID_Toshiba {
            get {
                return ResourceManager.GetString("Company_CpyID_Toshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name_B2B {
            get {
                return ResourceManager.GetString("Company_Name_B2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Company_Name_B2C {
            get {
                return ResourceManager.GetString("Company_Name_B2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string Company_NationalID {
            get {
                return ResourceManager.GetString("Company_NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string Company_NationalID_Arrow {
            get {
                return ResourceManager.GetString("Company_NationalID_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor.
        /// </summary>
        public static string Competitor_Name {
            get {
                return ResourceManager.GetString("Competitor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string Competitor_Name_Birmingham {
            get {
                return ResourceManager.GetString("Competitor_Name_Birmingham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string Competitor_Name_SLM {
            get {
                return ResourceManager.GetString("Competitor_Name_SLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Competitor_Name_XCT {
            get {
                return ResourceManager.GetString("Competitor_Name_XCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Contact_CtcID {
            get {
                return ResourceManager.GetString("Contact_CtcID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ID.
        /// </summary>
        public static string Contact_CtcID_Toshiba {
            get {
                return ResourceManager.GetString("Contact_CtcID_Toshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MarketingCampaign_CampaignTitle {
            get {
                return ResourceManager.GetString("MarketingCampaign_CampaignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Group.
        /// </summary>
        public static string MarketingCampaign_CGPercent {
            get {
                return ResourceManager.GetString("MarketingCampaign_CGPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to remain in CG.
        /// </summary>
        public static string MarketingCampaign_DaysToRemainInCG {
            get {
                return ResourceManager.GetString("MarketingCampaign_DaysToRemainInCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due/Start Date.
        /// </summary>
        public static string MarketingCampaign_DueDate {
            get {
                return ResourceManager.GetString("MarketingCampaign_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude CG from.
        /// </summary>
        public static string MarketingCampaign_ExcludeCGFromAllCampaigns {
            get {
                return ResourceManager.GetString("MarketingCampaign_ExcludeCGFromAllCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration/End Date.
        /// </summary>
        public static string MarketingCampaign_ExpiryDate {
            get {
                return ResourceManager.GetString("MarketingCampaign_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Code.
        /// </summary>
        public static string MarketingCampaign_ID {
            get {
                return ResourceManager.GetString("MarketingCampaign_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Originator.
        /// </summary>
        public static string MarketingCampaign_Originator {
            get {
                return ResourceManager.GetString("MarketingCampaign_Originator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Profile.
        /// </summary>
        public static string MarketingCampaign_SenderValueName {
            get {
                return ResourceManager.GetString("MarketingCampaign_SenderValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Raised.
        /// </summary>
        public static string MarketingCampaign_SubmittedOn {
            get {
                return ResourceManager.GetString("MarketingCampaign_SubmittedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MarketingCampaign_SubType {
            get {
                return ResourceManager.GetString("MarketingCampaign_SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Total Comms.
        /// </summary>
        public static string MarketingCampaign_TotalComms {
            get {
                return ResourceManager.GetString("MarketingCampaign_TotalComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Total Cost.
        /// </summary>
        public static string MarketingCampaign_TotalCost {
            get {
                return ResourceManager.GetString("MarketingCampaign_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Targeted Customers.
        /// </summary>
        public static string MarketingCampaign_TotalTargetedCustomers {
            get {
                return ResourceManager.GetString("MarketingCampaign_TotalTargetedCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved On.
        /// </summary>
        public static string MarketingCampaign_URD {
            get {
                return ResourceManager.GetString("MarketingCampaign_URD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string Person_DOB {
            get {
                return ResourceManager.GetString("Person_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Person_DOB_Toshiba {
            get {
                return ResourceManager.GetString("Person_DOB_Toshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        public static string Preferences_CpyID_B2B {
            get {
                return ResourceManager.GetString("Preferences_CpyID_B2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household ID.
        /// </summary>
        public static string Preferences_CpyID_B2C {
            get {
                return ResourceManager.GetString("Preferences_CpyID_B2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ID.
        /// </summary>
        public static string Preferences_CtcID {
            get {
                return ResourceManager.GetString("Preferences_CtcID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Preferences_CtcID_SLM {
            get {
                return ResourceManager.GetString("Preferences_CtcID_SLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store_Name {
            get {
                return ResourceManager.GetString("Store_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catchment.
        /// </summary>
        public static string Store_Name_Birmingham {
            get {
                return ResourceManager.GetString("Store_Name_Birmingham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string Store_Name_SLM {
            get {
                return ResourceManager.GetString("Store_Name_SLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Store_Name_XCT {
            get {
                return ResourceManager.GetString("Store_Name_XCT", resourceCulture);
            }
        }
    }
}
