//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a asset.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atreemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a asset like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atreemo.Resources.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Icons.
        /// </summary>
        public static string Icon_EditIconsBtn {
            get {
                return ResourceManager.GetString("Icon_EditIconsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon set.
        /// </summary>
        public static string Icon_NewSet {
            get {
                return ResourceManager.GetString("Icon_NewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string IconCriteria_Label {
            get {
                return ResourceManager.GetString("IconCriteria_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon to Edit.
        /// </summary>
        public static string IconEdit_Title {
            get {
                return ResourceManager.GetString("IconEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string IconFileName_Label {
            get {
                return ResourceManager.GetString("IconFileName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Group name.
        /// </summary>
        public static string IconGroupName_Label {
            get {
                return ResourceManager.GetString("IconGroupName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Name.
        /// </summary>
        public static string IconName_Label {
            get {
                return ResourceManager.GetString("IconName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note icons should be xxx px x xxx px.
        /// </summary>
        public static string IconNote {
            get {
                return ResourceManager.GetString("IconNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string IconSelectionCount {
            get {
                return ResourceManager.GetString("IconSelectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon set to Edit.
        /// </summary>
        public static string IconSetEdit_Title {
            get {
                return ResourceManager.GetString("IconSetEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string IconSrc_Label {
            get {
                return ResourceManager.GetString("IconSrc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string IconUpdate_Label {
            get {
                return ResourceManager.GetString("IconUpdate_Label", resourceCulture);
            }
        }
    }
}
